//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak_1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BetweenUsEntities : DbContext
    {
        public BetweenUsEntities()
            : base("name=BetweenUsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblLikedPost> tblLikedPosts { get; set; }
        public virtual DbSet<tblPost> tblPosts { get; set; }
        public virtual DbSet<tblRequest> tblRequests { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<vwFriendPost> vwFriendPosts { get; set; }
        public virtual DbSet<vwPost> vwPosts { get; set; }
        public virtual DbSet<vwRequest> vwRequests { get; set; }
        public virtual DbSet<vwUser> vwUsers { get; set; }
    }
}
