//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwFriendPost
    {
        public int PostId { get; set; }
        public int UserId { get; set; }
        public string PostContent { get; set; }
        public System.DateTime DateOfPost { get; set; }
        public int NumberOfLikes { get; set; }
        public int RecipientId { get; set; }
        public int SenderId { get; set; }
        public string User { get; set; }
        public string Username { get; set; }
    }
}
