//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRequest
    {
        public int RequestId { get; set; }
        public int SenderId { get; set; }
        public int RecipientId { get; set; }
        public string Status { get; set; }
        public string Sender { get; set; }
        public string Recipient { get; set; }
        public string SenderUsename { get; set; }
        public string RecipientUsername { get; set; }
    }
}
